// Mapa simples de nome da selecao -> emoji de bandeira, para exibir um "escudo"
// leve sem depender de imagens externas. Cobre as principais selecoes; quando
// nao encontra, mostra um icone neutro de bola.
export const BANDEIRAS = {
  Argentina: "🇦🇷",
  Brazil: "🇧🇷",
  Brasil: "🇧🇷",
  France: "🇫🇷",
  França: "🇫🇷",
  England: "🏴",
  Inglaterra: "🏴",
  Spain: "🇪🇸",
  Espanha: "🇪🇸",
  Germany: "🇩🇪",
  Alemanha: "🇩🇪",
  Portugal: "🇵🇹",
  Netherlands: "🇳🇱",
  Holanda: "🇳🇱",
  Belgium: "🇧🇪",
  Bélgica: "🇧🇪",
  Italy: "🇮🇹",
  Itália: "🇮🇹",
  Croatia: "🇭🇷",
  Croácia: "🇭🇷",
  Uruguay: "🇺🇾",
  Uruguai: "🇺🇾",
  Mexico: "🇲🇽",
  México: "🇲🇽",
  "United States": "🇺🇸",
  USA: "🇺🇸",
  Canada: "🇨🇦",
  Canadá: "🇨🇦",
  Japan: "🇯🇵",
  Japão: "🇯🇵",
  "South Korea": "🇰🇷",
  Morocco: "🇲🇦",
  Marrocos: "🇲🇦",
  Senegal: "🇸🇳",
  Ghana: "🇬🇭",
  Nigeria: "🇳🇬",
  Cameroon: "🇨🇲",
  Colombia: "🇨🇴",
  Colômbia: "🇨🇴",
  Ecuador: "🇪🇨",
  Equador: "🇪🇨",
  Peru: "🇵🇪",
  Chile: "🇨🇱",
  Paraguay: "🇵🇾",
  Switzerland: "🇨🇭",
  Suíça: "🇨🇭",
  Denmark: "🇩🇰",
  Dinamarca: "🇩🇰",
  Poland: "🇵🇱",
  Polônia: "🇵🇱",
  Serbia: "🇷🇸",
  Sérvia: "🇷🇸",
  Austria: "🇦🇹",
  Áustria: "🇦🇹",
  "Czech Republic": "🇨🇿",
  Australia: "🇦🇺",
  Austrália: "🇦🇺",
  "Saudi Arabia": "🇸🇦",
  Iran: "🇮🇷",
  Qatar: "🇶🇦",
  Tunisia: "🇹🇳",
  Tunísia: "🇹🇳",
  Egypt: "🇪🇬",
  Egito: "🇪🇬",
  Algeria: "🇩🇿",
  Argélia: "🇩🇿",
  "South Africa": "🇿🇦",
  "Costa Rica": "🇨🇷",
  Panama: "🇵🇦",
  Panamá: "🇵🇦",
  Jamaica: "🇯🇲",
  Scotland: "🏴",
  Wales: "🏴",
  Norway: "🇳🇴",
  Noruega: "🇳🇴",
  Sweden: "🇸🇪",
  Suécia: "🇸🇪",
  Turkey: "🇹🇷",
  Turquia: "🇹🇷",
  Greece: "🇬🇷",
  Grécia: "🇬🇷",
  Ukraine: "🇺🇦",
  Ucrânia: "🇺🇦",
  "El Salvador": "🇸🇻",
  "Trinidad e Tobago": "🇹🇹",
  Trinidad: "🇹🇹",
  Bolivia: "🇧🇴",
  Bolívia: "🇧🇴",
  Venezuela: "🇻🇪",
  Honduras: "🇭🇳",
  Mali: "🇲🇱",
  Camarões: "🇨🇲",
  Nigéria: "🇳🇬",
  "Estados Unidos": "🇺🇸",
  "Coreia do Sul": "🇰🇷",
  "Arábia Saudita": "🇸🇦",
  Irã: "🇮🇷",
  Catar: "🇶🇦",
  "República Tcheca": "🇨🇿",
  "República Democrática do Congo": "🇨🇩",
  "Rep. Democrática do Congo": "🇨🇩",
  "Bósnia e Herzegovina": "🇧🇦",
  "África do Sul": "🇿🇦",
  "Costa do Marfim": "🇨🇮",
  Curaçau: "🇨🇼",
  "Nova Zelândia": "🇳🇿",
  "Cabo Verde": "🇨🇻",
  Iraque: "🇮🇶",
  Noruega: "🇳🇴",
  Argélia: "🇩🇿",
  Áustria: "🇦🇹",
  Jordânia: "🇯🇴",
  Uzbequistão: "🇺🇿",
  Escócia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Haiti: "🇭🇹",
  Paraguai: "🇵🇾",
  Egito: "🇪🇬",
  Gana: "🇬🇭",
};

export function bandeira(nome) {
  if (!nome) return "⚽";
  return BANDEIRAS[nome] || BANDEIRAS[nome.trim()] || "⚽";
}
